export const categoryOptions = [
  { value: "fashion", label: "Thời trang" },
  { value: "skincare", label: "Mỹ phẩm / Skincare" },
  { value: "beautyTools", label: "Dụng cụ làm đẹp / Chăm sóc cá nhân" },
  { value: "home", label: "Gia dụng" },
  { value: "furnitureDecor", label: "Nội thất / Trang trí" },
  { value: "electronics", label: "Điện tử / Phụ kiện" },
  { value: "food", label: "Thực phẩm / Đồ uống" },
  { value: "householdEssentials", label: "Hàng tiêu dùng nhanh" },
  { value: "footwear", label: "Giày dép" },
  { value: "bags", label: "Túi xách / Ví" },
  { value: "accessories", label: "Phụ kiện" },
  { value: "fragrance", label: "Nước hoa / Hương thơm" },
  { value: "pet", label: "Thú cưng" },
  { value: "sports", label: "Thể thao / Fitness" },
  { value: "motherBaby", label: "Mẹ & Bé" },
  { value: "healthCare", label: "Sức khỏe" },
  { value: "booksStationery", label: "Sách / Văn phòng phẩm" },
  { value: "toysGames", label: "Đồ chơi / Board game" },
  { value: "autoMoto", label: "Ô tô / Xe máy / Xe đạp" },
  { value: "phoneTablet", label: "Điện thoại / Tablet" },
  { value: "computerOffice", label: "Máy tính / Thiết bị văn phòng" },
  { value: "cameraDrone", label: "Máy ảnh / Drone" },
  { value: "homeAppliances", label: "Điện gia dụng" },
  { value: "toolsHardware", label: "Dụng cụ / Cải tạo nhà" },
  { value: "digitalGoods", label: "Sản phẩm số / Voucher" },
  { value: "other", label: "Khác" }
];

export const channelOptions = ["TikTok Shop", "Shopee", "TikTok Shop + Shopee"];

export const subcategoryMap = {
  fashion: ["Thời trang nữ công sở", "Thời trang nam basic", "Thời trang bigsize", "Streetwear", "Đồ ngủ / mặc nhà"],
  skincare: ["Da mụn nhạy cảm", "Làm sáng da", "Phục hồi hàng rào", "Chống nắng", "Làm sạch"],
  beautyTools: ["Máy tạo kiểu tóc", "Thiết bị chăm sóc da", "Dụng cụ makeup", "Dụng cụ nail", "Dụng cụ vệ sinh cá nhân"],
  home: ["Gia dụng nhà bếp", "Dọn dẹp nhà cửa", "Decor phòng", "Lưu trữ", "Chăm sóc phòng ngủ"],
  furnitureDecor: ["Sofa / ghế", "Bàn / kệ", "Đèn trang trí", "Rèm / thảm", "Decor để bàn"],
  electronics: ["Phụ kiện điện thoại", "Tai nghe / gaming", "Smart home", "Sạc / pin", "Thiết bị văn phòng"],
  food: ["Đồ ăn vặt", "Đồ uống tiện lợi", "Eat-clean", "Quà tặng thực phẩm", "Gia vị / nấu nhanh"],
  householdEssentials: ["Giấy và khăn", "Nước giặt / xả", "Vệ sinh nhà bếp", "Chăm sóc nhà tắm", "Đồ dùng tiêu hao"],
  footwear: ["Sneaker", "Sandal", "Giày chạy bộ", "Giày công sở", "Dép hằng ngày"],
  bags: ["Túi công sở", "Túi mini đi chơi", "Balo đi học/đi làm", "Ví", "Túi du lịch"],
  accessories: ["Trang sức", "Mũ nón / kính", "Thắt lưng / khăn", "Đồng hồ", "Phụ kiện tóc"],
  fragrance: ["Nước hoa nữ", "Nước hoa nam", "Hương thơm phòng", "Body mist", "Tinh dầu"],
  pet: ["Mèo - thức ăn/snack", "Chó - chăm sóc", "Phụ kiện thú cưng", "Đồ chơi", "Vệ sinh thú cưng"],
  sports: ["Gym / tập lực", "Yoga / pilates", "Running", "Phụ kiện thể thao", "Bình nước"],
  motherBaby: ["Sữa / bỉm tã", "Đồ ăn dặm", "Đồ dùng sơ sinh", "Xe đẩy / địu", "Đồ chơi phát triển"],
  healthCare: ["Vitamin / khoáng chất", "Thiết bị theo dõi sức khỏe", "Hỗ trợ xương khớp", "Hỗ trợ giấc ngủ", "Chăm sóc cá nhân"],
  booksStationery: ["Sách kỹ năng", "Sách thiếu nhi", "Văn phòng phẩm", "Dụng cụ học tập", "Lịch / planner"],
  toysGames: ["Đồ chơi giáo dục", "Board game", "Lắp ráp", "Đồ chơi vận động", "Mô hình"],
  autoMoto: ["Phụ kiện xe máy", "Phụ kiện ô tô", "Mũ bảo hiểm", "Đồ chăm sóc xe", "Đồ điện xe"],
  phoneTablet: ["Điện thoại", "Máy tính bảng", "Ốp / kính cường lực", "Sạc / cáp", "Tai nghe"],
  computerOffice: ["Laptop", "Màn hình", "Bàn phím / chuột", "Thiết bị mạng", "Phụ kiện văn phòng"],
  cameraDrone: ["Camera hành động", "Camera an ninh", "Máy ảnh", "Drone", "Phụ kiện quay chụp"],
  homeAppliances: ["Máy xay / ép", "Nồi chiên / nồi điện", "Thiết bị hút bụi", "Lọc không khí", "Máy sưởi / quạt"],
  toolsHardware: ["Dụng cụ cầm tay", "Khoan / bắt vít", "Thiết bị đo", "Đồ bảo hộ", "Vật tư sửa chữa"],
  digitalGoods: ["Voucher điện tử", "Gift card", "Mã bản quyền phần mềm", "Khóa học online", "Gói dịch vụ số"],
  other: ["Phổ thông", "Theo mùa", "Quà tặng", "Lifestyle", "Khác"]
};

const subcategoryExtraMap = {
  fashion: ["Athleisure / sporty chic", "Y2K / cá tính", "Đầm dự tiệc", "Thời trang trẻ em", "Đồ đôi / couple"],
  skincare: ["Lão hóa / nếp nhăn", "Dưỡng ẩm chuyên sâu", "Body care", "Mặt nạ / treatment", "Chăm sóc tóc"],
  beautyTools: ["Máy uốn / duỗi tóc", "Máy rửa mặt", "Máy triệt lông", "Bộ cọ trang điểm", "Máy sấy mini"],
  home: ["Đồ giặt sấy", "Nhà tắm / toilet", "Đèn & chiếu sáng", "Đồ dùng bàn ăn", "Gia dụng thông minh"],
  furnitureDecor: ["Nội thất đa năng", "Kệ module", "Đèn LED trang trí", "Trang trí tối giản", "Decor phòng thuê"],
  electronics: ["Phụ kiện livestream", "Thiết bị học online", "Đồng hồ thông minh", "Phụ kiện laptop", "Thiết bị xe hơi"],
  food: ["Đồ đông lạnh", "Đồ khô pantry", "Đặc sản vùng miền", "Đồ uống healthy", "Thực phẩm cho mẹ bé"],
  householdEssentials: ["Nước lau sàn", "Viên giặt", "Giấy vệ sinh cao cấp", "Túi rác tự hủy", "Nước rửa chén dịu nhẹ"],
  footwear: ["Giày cao gót", "Giày búp bê", "Boots", "Giày trẻ em", "Giày leo núi / outdoor"],
  bags: ["Túi tote", "Túi laptop", "Túi thể thao", "Vali", "Túi mẹ bé"],
  accessories: ["Khuyên tai / nhẫn", "Phụ kiện tóc", "Thắt lưng da", "Phụ kiện unisex", "Phụ kiện thời trang mùa lễ"],
  fragrance: ["Nước hoa niche", "Nến thơm / sáp thơm", "Xịt thơm vải", "Nước hoa mini", "Khử mùi cơ thể"],
  pet: ["Cát vệ sinh", "Đệm / nhà thú cưng", "Phụ kiện đi dạo", "Vệ sinh răng miệng", "Vitamin thú cưng"],
  sports: ["Đạp xe", "Bơi lội", "Cầu lông / tennis", "Đồ tập tại nhà", "Thiết bị recovery"],
  motherBaby: ["Mẹ bầu", "Chăm sóc sau sinh", "Tắm gội cho bé", "Phòng ngủ cho bé", "Đồ đi học cho bé"],
  healthCare: ["Thiết bị y tế gia đình", "Chăm sóc răng miệng", "Hỗ trợ tiêu hóa", "Hỗ trợ miễn dịch", "Dụng cụ phục hồi"],
  booksStationery: ["Sách ngoại ngữ", "Sách kinh doanh", "Sổ tay / notebook", "Dụng cụ vẽ", "Desk setup"],
  toysGames: ["Đồ chơi sơ sinh", "Đồ chơi STEM", "Đồ chơi điều khiển", "Puzzle", "Đồ chơi nhập vai"],
  autoMoto: ["Camera hành trình", "Nội thất ô tô", "Bảo dưỡng định kỳ", "Đồ cứu hộ", "Phụ kiện xe đạp"],
  phoneTablet: ["Điện thoại gaming", "Tablet học tập", "Phụ kiện MagSafe", "Pin dự phòng", "Giá đỡ điện thoại"],
  computerOffice: ["PC / linh kiện", "Máy in / scan", "Lưu trữ dữ liệu", "Webcam / micro", "Bàn ghế công thái học"],
  cameraDrone: ["Ống kính", "Gimbal", "Đèn quay chụp", "Thẻ nhớ / lưu trữ", "Phụ kiện studio"],
  homeAppliances: ["Máy pha cà phê", "Máy giặt / sấy mini", "Thiết bị lọc nước", "Chăm sóc quần áo", "Thiết bị bếp thông minh"],
  toolsHardware: ["Dụng cụ làm vườn", "Sơn / hoàn thiện", "Điện nước dân dụng", "Khóa / an ninh", "Thang / nâng hạ"],
  digitalGoods: ["Mã game", "Mã xem phim", "Template số", "Preset chỉnh ảnh", "Gói lưu trữ cloud"],
  other: ["Handmade", "Digital goods", "Quà doanh nghiệp", "Đồ sưu tầm", "Dịch vụ kèm sản phẩm"]
};

function mergeSubcategoryMap(baseMap, extraMap) {
  for (const [category, extras] of Object.entries(extraMap)) {
    const baseList = Array.isArray(baseMap[category]) ? baseMap[category] : [];
    const seen = new Set(baseList.map((item) => String(item || "").toLowerCase().trim()));
    const mergedExtras = (Array.isArray(extras) ? extras : []).filter((item) => {
      const key = String(item || "").toLowerCase().trim();
      if (!key || seen.has(key)) return false;
      seen.add(key);
      return true;
    });
    baseMap[category] = [...baseList, ...mergedExtras];
  }
}

mergeSubcategoryMap(subcategoryMap, subcategoryExtraMap);

export const toneOptions = ["Review tự nhiên", "Chuyên gia", "Chốt sale mạnh"];
export const brandStyleOptions = ["Cao cấp tối giản", "Trẻ trung hiện đại", "Chuyên gia đáng tin", "Bình dân chỉn chu"];
export const moodOptions = ["Tinh gọn sang trọng", "Ấm áp gần gũi", "Năng động cuốn hút", "Tự tin thuyết phục"];

export const samplePresets = {
  fashion: {
    productName: "SERA - Set áo cổ sen phối ren và chân váy chữ A Selina",
    category: "fashion",
    subcategory: 4,
    channel: 2,
    tone: 1,
    brandStyle: 0,
    mood: 0,
    targetCustomer: "nữ yêu thích phong cách nữ tính và chỉn chu",
    shortDescription: "set thời trang nữ mang tinh thần thanh lịch, mềm mại và tinh tế",
    highlights: "cổ sen phối ren\nchân váy chữ A\nform lên dáng gọn",
    priceSegment: "phân khúc trung cao",
    attributes: "vải tex\nS, M, L\nmàu kem",
    sizeGuide: "S: 84-88 | M: 88-92 | L: 92-96",
    careGuide: "Giặt nhẹ, không ngâm lâu, ủi mặt trái",
    exchangePolicy: "Hỗ trợ đổi size 1 lần nếu còn tag"
  },
  skincare: {
    productName: "Serum phục hồi da B5 + Niacinamide",
    category: "skincare",
    subcategory: 0,
    channel: 2,
    tone: 1,
    brandStyle: 0,
    mood: 0,
    targetCustomer: "nữ 22 đến 35 tuổi, da khô và da nhạy cảm",
    shortDescription: "serum phục hồi, cấp ẩm và làm dịu da với kết cấu mỏng nhẹ",
    highlights: "thấm nhanh\nêm da\nhợp routine sáng tối",
    priceSegment: "329k",
    attributes: "Niacinamide, B5\nda khô, da nhạy cảm\nmỏng nhẹ, ráo nhanh",
    usage: "Dùng sáng và tối sau toner, trước kem dưỡng",
    skinConcern: "Khô ráp, thiếu ẩm, dễ kích ứng",
    routineStep: "Serum phục hồi / serum cấp ẩm"
  },
  beautyTools: {
    productName: "Máy rửa mặt sóng âm mini",
    category: "beautyTools",
    subcategory: 1,
    channel: 1,
    tone: 1,
    brandStyle: 2,
    mood: 1,
    targetCustomer: "người cần làm sạch da nhanh và đều mỗi ngày",
    shortDescription: "máy rửa mặt sóng âm làm sạch dịu, dễ dùng trong routine cá nhân tại nhà",
    highlights: "rung êm\ndễ vệ sinh\npin bền",
    priceSegment: "499k",
    attributes: "đầu silicone mềm\nchống nước IPX7\n3 mức rung",
    specs: "sóng âm làm sạch, sạc USB-C",
    compatibility: "da thường, da dầu, da hỗn hợp",
    warranty: "Bảo hành 12 tháng"
  },
  electronics: {
    productName: "Tai nghe bluetooth chống ồn",
    category: "electronics",
    subcategory: 0,
    channel: 1,
    tone: 1,
    brandStyle: 0,
    mood: 0,
    targetCustomer: "người đi làm và người thích setup gọn gàng",
    shortDescription: "tai nghe gọn, đeo êm, chống ồn và pin lâu",
    highlights: "chống ồn chủ động\nkết nối ổn định\npin bền bỉ",
    priceSegment: "1.290k",
    attributes: "chống ồn, cảm ứng\nBluetooth 5.3\npin 30 giờ",
    specs: "Bluetooth 5.3, pin 30h",
    compatibility: "iOS, Android, laptop",
    warranty: "Bảo hành 12 tháng"
  },
  home: {
    productName: "Kệ để bàn đa năng tối giản",
    category: "home",
    subcategory: 0,
    channel: 1,
    tone: 1,
    brandStyle: 0,
    mood: 0,
    targetCustomer: "người làm việc tại nhà và người thích không gian gọn gàng",
    shortDescription: "thiết kế gọn, dễ sắp xếp đồ và phù hợp nhiều góc làm việc",
    highlights: "dễ vệ sinh\nbố cục ngăn hợp lý\nphù hợp bàn nhỏ",
    priceSegment: "459k",
    attributes: "đa công năng\n32 x 18 x 20 cm\ngỗ phủ melamine",
    dimensions: "32 x 18 x 20 cm",
    warranty: "Bảo hành 6 tháng",
    usageSpace: "Bàn làm việc, bếp, phòng ngủ"
  },
  furnitureDecor: {
    productName: "Đèn bàn decor ánh sáng 3 mức",
    category: "furnitureDecor",
    subcategory: 2,
    channel: 1,
    tone: 0,
    brandStyle: 1,
    mood: 0,
    targetCustomer: "người thích setup góc làm việc và phòng ngủ có gu",
    shortDescription: "đèn bàn decor ánh sáng dịu, thiết kế tối giản, dễ phối nhiều không gian",
    highlights: "3 mức sáng\nthiết kế tối giản\ndễ đặt góc nhỏ",
    priceSegment: "369k",
    attributes: "nhôm sơn tĩnh điện\nđiều chỉnh góc\nmàu trắng kem",
    dimensions: "42 x 15 x 15 cm",
    usageSpace: "Bàn làm việc, tab đầu giường",
    warranty: "Bảo hành 6 tháng"
  },
  food: {
    productName: "Granola hạt mix vị cacao",
    category: "food",
    subcategory: 0,
    channel: 2,
    tone: 0,
    brandStyle: 1,
    mood: 1,
    targetCustomer: "dân văn phòng và người thích đồ ăn nhẹ lành mạnh",
    shortDescription: "granola giòn nhẹ, dễ ăn và tiện dùng trong ngày",
    highlights: "giòn nhẹ\ndễ mang theo\nvị cacao vừa miệng",
    priceSegment: "129k",
    attributes: "yến mạch, hạt điều, hạnh nhân\nvị cacao\nhũ 300g"
  },
  householdEssentials: {
    productName: "Viên giặt đậm đặc hương dịu",
    category: "householdEssentials",
    subcategory: 1,
    channel: 2,
    tone: 0,
    brandStyle: 3,
    mood: 1,
    targetCustomer: "gia đình bận rộn cần giặt nhanh và sạch ổn định",
    shortDescription: "viên giặt hòa tan nhanh, làm sạch tốt và giữ mùi hương nhẹ dễ chịu",
    highlights: "hòa tan nhanh\ntiện định lượng\nhương dịu",
    priceSegment: "189k",
    attributes: "hộp 40 viên\nphù hợp máy cửa trước\nít bọt",
    usage: "1 viên cho 6-8kg quần áo",
    dimensions: "Hộp 18 x 12 x 10 cm"
  },
  footwear: {
    productName: "Sneaker đế êm phối màu tối giản",
    category: "footwear",
    subcategory: 0,
    channel: 2,
    tone: 1,
    brandStyle: 0,
    mood: 0,
    targetCustomer: "người thích outfit gọn và ưu tiên độ êm chân hằng ngày",
    shortDescription: "sneaker gọn dáng, đế êm và dễ kết hợp cùng nhiều outfit thường nhật",
    highlights: "đế êm\nform gọn\nphối đồ linh hoạt",
    priceSegment: "890k",
    attributes: "da tổng hợp / canvas\n36-39\ntrắng kem"
  },
  bags: {
    productName: "Túi đeo vai mini form cứng",
    category: "bags",
    subcategory: 0,
    channel: 2,
    tone: 1,
    brandStyle: 0,
    mood: 0,
    targetCustomer: "nữ trẻ theo phong cách tối giản và thanh lịch",
    shortDescription: "form túi gọn, cứng cáp và đủ tinh tế để đi làm hoặc đi chơi nhẹ",
    highlights: "form cứng giữ dáng\nngăn chứa gọn\nphối đồ dễ",
    priceSegment: "459k",
    attributes: "da PU mềm\n22 x 14 cm\nden bong nhe"
  },
  motherBaby: {
    productName: "Bình sữa chống sặc cổ rộng",
    category: "motherBaby",
    subcategory: 2,
    channel: 2,
    tone: 1,
    brandStyle: 2,
    mood: 1,
    targetCustomer: "mẹ bỉm muốn đồ cho bé an toàn, dễ vệ sinh",
    shortDescription: "bình sữa cổ rộng chống sặc, cầm chắc tay và dễ làm sạch sau mỗi lần dùng",
    highlights: "van khí chống đầy hơi\nchất liệu an toàn\ndễ thay núm",
    priceSegment: "219k",
    attributes: "nhựa PPSU\n160ml\nnúm ti mềm",
    compatibility: "Phù hợp núm cổ rộng cùng chuẩn",
    warranty: "Đổi lỗi 7 ngày"
  },
  healthCare: {
    productName: "Máy đo huyết áp bắp tay tự động",
    category: "healthCare",
    subcategory: 1,
    channel: 1,
    tone: 1,
    brandStyle: 2,
    mood: 3,
    targetCustomer: "người trưởng thành cần theo dõi huyết áp tại nhà",
    shortDescription: "thiết bị đo huyết áp dễ dùng, hiển thị rõ và hỗ trợ lưu kết quả đo",
    highlights: "đo nhanh\nmàn hình lớn\nlưu nhiều kết quả",
    priceSegment: "899k",
    attributes: "cảm biến ổn định\npin AAA\nvòng bít cỡ chuẩn",
    specs: "Đo dao động, hiển thị SYS/DIA/Pulse",
    warranty: "Bảo hành 12 tháng"
  },
  booksStationery: {
    productName: "Planner tuần A5 kèm sticker",
    category: "booksStationery",
    subcategory: 4,
    channel: 0,
    tone: 0,
    brandStyle: 1,
    mood: 1,
    targetCustomer: "học sinh, sinh viên và dân văn phòng thích lập kế hoạch",
    shortDescription: "planner tuần bố cục rõ, giấy dày và nhiều trang theo dõi mục tiêu",
    highlights: "bố cục dễ dùng\ngiấy dày\nthiết kế gọn",
    priceSegment: "149k",
    attributes: "A5\n120 trang\nkèm sticker"
  },
  toysGames: {
    productName: "Board game chiến thuật gia đình 2-6 người",
    category: "toysGames",
    subcategory: 1,
    channel: 2,
    tone: 0,
    brandStyle: 1,
    mood: 2,
    targetCustomer: "gia đình có trẻ từ 8 tuổi và nhóm bạn thích board game",
    shortDescription: "board game chiến thuật dễ nhập cuộc, tăng tương tác và phù hợp nhiều dịp tụ họp",
    highlights: "luật dễ hiểu\nnhịp chơi nhanh\nchơi lại không chán",
    priceSegment: "359k",
    attributes: "2-6 người\n45 phút/ván\nthẻ ép cứng"
  },
  autoMoto: {
    productName: "Giá đỡ điện thoại cho xe máy chống rung",
    category: "autoMoto",
    subcategory: 0,
    channel: 2,
    tone: 1,
    brandStyle: 2,
    mood: 3,
    targetCustomer: "người đi xe máy thường xuyên cần xem bản đồ an toàn",
    shortDescription: "giá đỡ điện thoại chống rung, kẹp chắc và xoay góc linh hoạt khi di chuyển",
    highlights: "kẹp chắc\nchống rung\ndễ lắp",
    priceSegment: "199k",
    attributes: "hợp tay lái 22-32mm\nxoay 360\nhợp điện thoại 4.7-6.8 inch",
    compatibility: "Phù hợp đa số xe số/xe ga",
    warranty: "Bảo hành 6 tháng"
  },
  phoneTablet: {
    productName: "Tablet 10.4 inch pin lớn",
    category: "phoneTablet",
    subcategory: 1,
    channel: 1,
    tone: 1,
    brandStyle: 2,
    mood: 3,
    targetCustomer: "người học online và giải trí cơ bản",
    shortDescription: "tablet màn lớn dễ nhìn, pin dùng dài và đủ mượt cho nhu cầu hằng ngày",
    highlights: "màn hình rộng\npin bền\nâm thanh rõ",
    priceSegment: "5.990k",
    attributes: "10.4 inch\nRAM 6GB\nbộ nhớ 128GB",
    specs: "Wi-Fi 6, pin 7000mAh",
    compatibility: "Hỗ trợ bút cảm ứng chuẩn phổ biến",
    warranty: "Bảo hành 12 tháng"
  },
  computerOffice: {
    productName: "Bàn phím cơ layout 84 phím",
    category: "computerOffice",
    subcategory: 2,
    channel: 0,
    tone: 1,
    brandStyle: 1,
    mood: 2,
    targetCustomer: "dân văn phòng và người làm việc từ xa",
    shortDescription: "bàn phím cơ gọn, gõ êm tay và dễ setup theo phong cách bàn làm việc hiện đại",
    highlights: "layout gọn\nkeycap chắc\nkết nối linh hoạt",
    priceSegment: "1.290k",
    attributes: "84 phím\nhot-swap\nRGB nhẹ",
    specs: "Bluetooth + 2.4G + dây USB-C",
    compatibility: "Windows, macOS, iPadOS",
    warranty: "Bảo hành 12 tháng"
  },
  cameraDrone: {
    productName: "Camera hành trình 4K góc rộng",
    category: "cameraDrone",
    subcategory: 0,
    channel: 1,
    tone: 1,
    brandStyle: 2,
    mood: 3,
    targetCustomer: "người thường xuyên di chuyển và muốn ghi lại hành trình",
    shortDescription: "camera hành trình chất lượng cao, ghi hình rõ nét và dễ quản lý file qua ứng dụng",
    highlights: "ghi 4K\ngóc rộng\ndễ xem lại",
    priceSegment: "2.490k",
    attributes: "ống kính 170 độ\nchống rung điện tử\nthu âm rõ",
    specs: "4K30fps, Wi-Fi, khe thẻ nhớ",
    warranty: "Bảo hành 12 tháng"
  },
  homeAppliances: {
    productName: "Nồi chiên không dầu 6L",
    category: "homeAppliances",
    subcategory: 1,
    channel: 2,
    tone: 1,
    brandStyle: 3,
    mood: 2,
    targetCustomer: "gia đình 2-4 người cần nấu ăn nhanh và gọn",
    shortDescription: "nồi chiên dung tích lớn, dễ thao tác và hỗ trợ nấu nhanh nhiều món hằng ngày",
    highlights: "6L rộng rãi\nmenu tiện\ndễ vệ sinh",
    priceSegment: "2.190k",
    attributes: "công suất 1700W\nrổ chống dính\nmàn hình cảm ứng",
    dimensions: "36 x 30 x 33 cm",
    usageSpace: "Bếp gia đình",
    warranty: "Bảo hành 24 tháng"
  },
  toolsHardware: {
    productName: "Máy khoan pin không chổi than",
    category: "toolsHardware",
    subcategory: 1,
    channel: 1,
    tone: 1,
    brandStyle: 2,
    mood: 3,
    targetCustomer: "thợ kỹ thuật và người thích tự sửa chữa tại nhà",
    shortDescription: "máy khoan pin lực ổn định, gọn tay và phù hợp cả nhu cầu gia đình lẫn công việc cơ bản",
    highlights: "lực khoan khỏe\npin tháo rời\nđiều tốc mượt",
    priceSegment: "1.790k",
    attributes: "motor không chổi than\npin 20V\nđèn LED",
    specs: "2 cấp tốc độ, 21 cấp lực siết",
    warranty: "Bảo hành 12 tháng"
  },
  digitalGoods: {
    productName: "Gói template social media 200 mẫu",
    category: "digitalGoods",
    subcategory: 0,
    channel: 2,
    tone: 1,
    brandStyle: 2,
    mood: 2,
    targetCustomer: "creator và shop nhỏ cần sản xuất nội dung nhanh",
    shortDescription: "bộ template social media kéo thả, tiết kiệm thời gian thiết kế cho post bán hàng",
    highlights: "dễ chỉnh sửa\nđa nền tảng\ntiết kiệm thời gian",
    priceSegment: "299k",
    attributes: "200 mẫu\nfile Canva\ncập nhật hàng tháng",
    specs: "file số tải ngay",
    compatibility: "Canva web/mobile",
    warranty: "Hỗ trợ cập nhật 3 tháng"
  },
  other: {
    productName: "Set quà tặng lifestyle tối giản",
    category: "other",
    subcategory: 0,
    channel: 2,
    tone: 0,
    brandStyle: 0,
    mood: 1,
    targetCustomer: "người mua quà cần đẹp, dễ tặng và hữu ích thực tế",
    shortDescription: "set quà tặng gồm nhiều món cơ bản, đóng gói chỉn chu và phù hợp nhiều dịp",
    highlights: "đóng gói đẹp\ndễ tặng\ngiá hợp lý",
    priceSegment: "299k",
    attributes: "hộp quà cứng\n3-5 món\nthiết kế trung tính"
  }
};

export const categoryHints = {
  fashion: { short: "Thiết kế gọn gàng, dễ mặc, tôn dáng và giữ cảm giác chỉn chu.", highlights: "Cổ sen phối ren\nForm chữ A tôn dáng\nMặc đi làm hoặc đi chơi", attrs: "vải tex\nS, M, L\nmàu kem", target: "Khách hàng yêu thích sự chỉn chu, thanh lịch hoặc đồ mặc nhà tinh tế..." },
  skincare: { short: "Kết cấu mỏng nhẹ, dễ dùng hằng ngày và phù hợp nhiều routine.", highlights: "Thấm nhanh không bết\nDịu nhẹ cho da nhạy cảm\nDùng sáng và tối", attrs: "Niacinamide, B5\nda khô, da nhạy cảm\nmỏng nhẹ, ráo nhanh", target: "Da khô, da nhạy cảm, người muốn routine tối giản nhưng hiệu quả..." },
  beautyTools: { short: "Dụng cụ làm đẹp ưu tiên hiệu quả thực tế, dễ thao tác và an toàn cho routine hằng ngày.", highlights: "Thao tác nhanh\nDễ vệ sinh\nDùng đều mỗi ngày", attrs: "chuẩn chống nước\nđầu tiếp xúc êm\nsạc tiện", target: "Người muốn chăm sóc cá nhân gọn, dễ duy trì và tiết kiệm thời gian..." },
  home: { short: "Thiết kế tiện dụng, gọn gàng và phù hợp nhiều không gian sống.", highlights: "Lắp đặt nhanh\nTối ưu góc làm việc\nDễ phối cùng nội thất", attrs: "đa công năng\n32 x 18 x 20 cm\ngỗ phủ melamine", target: "Người ở căn hộ, gia đình trẻ, người thích không gian gọn gàng..." },
  furnitureDecor: { short: "Nội thất và decor giúp không gian sống rõ gu, hài hòa và tiện dụng hơn mỗi ngày.", highlights: "Tăng thẩm mỹ\nDễ bố trí\nPhù hợp nhiều không gian", attrs: "kích thước gọn\nchất liệu bền\ntone dễ phối", target: "Người thích setup nhà cửa có gu, tối ưu diện tích nhưng vẫn đẹp mắt..." },
  electronics: { short: "Thiết bị gọn, rõ công năng và hữu ích trong nhịp dùng hằng ngày.", highlights: "Kết nối nhanh\nPin ổn định\nDễ thao tác", attrs: "chống ồn, cảm ứng\nBluetooth 5.3\npin 30 giờ", target: "Người đi làm, dân công nghệ, người thích setup gọn..." },
  food: { short: "Hương vị dễ dùng, tiện mang theo và rõ thành phần.", highlights: "Giòn nhẹ dễ ăn\nNgọt vừa\nTiện mang đi", attrs: "yến mạch, hạnh nhân\nvị cacao\nhũ 300g", target: "Dân văn phòng, người thích đồ ăn nhẹ lành mạnh, người bận rộn..." },
  householdEssentials: { short: "Hàng tiêu dùng nhanh ưu tiên tiện lợi, tiết kiệm và dễ dùng lặp lại mỗi ngày.", highlights: "Tiện định lượng\nDùng nhanh\nHiệu quả ổn định", attrs: "đóng gói gọn\nthành phần rõ\nhợp nhiều nhu cầu", target: "Gia đình và người sống bận rộn cần giải pháp tiêu dùng nhanh, đơn giản..." },
  footwear: { short: "Form giày gọn, dễ đi và hoàn thiện outfit rõ hơn.", highlights: "Đế êm\nÔm chân vừa\nDễ phối đồ", attrs: "da tổng hợp / canvas\n36-39\ntrắng kem", target: "Người ưu tiên độ êm chân và tính ứng dụng hằng ngày..." },
  bags: { short: "Thiết kế gọn, sang và dễ phối cùng nhiều outfit thường ngày.", highlights: "Form túi đứng dáng\nNgăn chứa vừa đủ\nĐeo vai nhẹ", attrs: "da PU mềm\n22 x 14 cm\nden bong nhe", target: "Người thích phụ kiện gọn, chỉn chu và dễ mang theo..." },
  accessories: { short: "Điểm nhấn nhỏ nhưng đủ nâng tổng thể trang phục gọn và có gu hơn.", highlights: "Hoàn thiện outfit\nDễ phối màu\nNhìn tinh tế hơn", attrs: "kim loại mạ / vải\nfree size\nbe / den", target: "Người thích hoàn thiện outfit bằng những chi tiết tinh tế..." },
  fragrance: { short: "Mùi hương tinh gọn, dễ tạo thiện cảm và phù hợp nhiều ngữ cảnh dùng.", highlights: "Mood sạch hiện đại\nDùng đi làm hoặc đi chơi\nLưu hương dễ chịu", attrs: "hương hoa gỗ\n50ml\nđộ lưu hương 6-8h", target: "Người thích mùi hương sạch, hiện đại và dễ dùng hằng ngày..." },
  pet: { short: "Sản phẩm tiện dụng, an tâm và phù hợp nhu cầu chăm sóc thú cưng hằng ngày.", highlights: "An toàn khi dùng\nDễ vệ sinh\nTiện cho lịch sinh hoạt", attrs: "cho chó mèo nhỏ\nvải mềm / thành phần rõ ràng\ndễ vệ sinh", target: "Người nuôi tìm giải pháp an toàn, gọn và đáng tin cho thú cưng..." },
  sports: { short: "Thiết kế thực dụng, bền và tạo cảm giác sẵn sàng cho nhịp vận động.", highlights: "Cầm nắm chắc\nĐộ bền tốt\nDễ mang theo", attrs: "vải co giãn / nhựa bền\nfree size / 750ml\nphù hợp gym, yoga, chạy bộ", target: "Người tập luyện thường xuyên, ưu tiên độ bền và sự tiện dụng..." },
  motherBaby: { short: "Ưu tiên an toàn, dễ vệ sinh và tiện cho nhịp chăm bé hằng ngày.", highlights: "Chất liệu an toàn\nDễ vệ sinh\nThiết kế thân thiện", attrs: "PPSU/silicone an toàn\nkích cỡ phù hợp\nhướng dẫn dùng rõ", target: "Mẹ bỉm và gia đình cần sản phẩm đáng tin, dễ dùng cho bé..." },
  healthCare: { short: "Nội dung cần rõ tính thực dụng, dễ hiểu và hỗ trợ theo dõi/chăm sóc tại nhà.", highlights: "Đo nhanh\nHiển thị rõ\nDễ thao tác", attrs: "thông số cốt lõi\nnguồn điện\nhướng dẫn dùng", target: "Người cần theo dõi sức khỏe cơ bản tại nhà một cách chủ động..." },
  booksStationery: { short: "Nhấn vào tính tiện dụng, trải nghiệm viết/đọc và khả năng duy trì thói quen học tập.", highlights: "Bố cục rõ\nDễ dùng mỗi ngày\nThiết kế gọn", attrs: "khổ giấy/chất giấy\nsố trang\nphụ kiện kèm", target: "Học sinh, sinh viên và dân văn phòng ưu tiên công cụ gọn, hiệu quả..." },
  toysGames: { short: "Ưu tiên độ an toàn, tính tương tác và giá trị giải trí/giáo dục rõ ràng.", highlights: "Luật dễ hiểu\nTăng tương tác\nChơi lại nhiều lần", attrs: "độ tuổi phù hợp\nsố người chơi\nchất liệu", target: "Gia đình và nhóm bạn muốn hoạt động giải trí lành mạnh, dễ kết nối..." },
  autoMoto: { short: "Nhấn vào độ bền, độ ổn định khi di chuyển và tính an toàn khi sử dụng thực tế.", highlights: "Lắp nhanh\nChắc chắn\nDùng ổn định", attrs: "chuẩn lắp\nchất liệu\nmức tương thích", target: "Người đi xe thường xuyên cần phụ kiện bền, gọn và đáng tin..." },
  phoneTablet: { short: "Tập trung vào trải nghiệm màn hình, pin, hiệu năng thực tế và độ tiện trong sinh hoạt hằng ngày.", highlights: "Màn hình rõ\nPin bền\nDùng mượt", attrs: "kích thước màn\nRAM/ROM\nkết nối", target: "Người học tập, làm việc nhẹ và giải trí hằng ngày trên thiết bị di động..." },
  computerOffice: { short: "Làm rõ hiệu quả công việc, độ ổn định và mức tiện dụng trong setup bàn làm việc.", highlights: "Kết nối ổn\nDễ setup\nTăng hiệu suất", attrs: "chuẩn kết nối\nkích thước\ntương thích hệ điều hành", target: "Dân văn phòng, freelancer và người làm việc từ xa cần thiết bị ổn định..." },
  cameraDrone: { short: "Nhấn vào chất lượng hình ảnh, độ ổn định quay và sự tiện lợi khi sử dụng ngoài thực tế.", highlights: "Hình ảnh rõ\nChống rung\nDễ quản lý file", attrs: "độ phân giải\ngóc quay\nchuẩn lưu trữ", target: "Người cần ghi hình hành trình, sáng tạo nội dung hoặc giám sát cơ bản..." },
  homeAppliances: { short: "Nội dung nên đặt sản phẩm vào bối cảnh bếp/nhà thật, nhấn vào tiện lợi và tiết kiệm thời gian.", highlights: "Nấu nhanh\nDễ vệ sinh\nPhù hợp gia đình", attrs: "công suất\ndung tích\nmenu/chế độ", target: "Gia đình trẻ và người bận rộn muốn tối ưu việc nhà mỗi ngày..." },
  toolsHardware: { short: "Ưu tiên độ bền, lực vận hành và sự chủ động khi sửa chữa/lắp đặt trong tình huống thực tế.", highlights: "Lực khỏe\nĐiều khiển dễ\nBền bỉ", attrs: "công suất/pin\ncấp tốc độ\nphụ kiện đi kèm", target: "Người tự sửa chữa tại nhà và thợ kỹ thuật cần công cụ tin cậy..." },
  digitalGoods: { short: "Sản phẩm số cần mô tả rõ giá trị sử dụng ngay, phạm vi truy cập và lợi ích tiết kiệm thời gian.", highlights: "Nhận ngay sau thanh toán\nDễ áp dụng\nTăng hiệu suất", attrs: "định dạng file\nquyền truy cập\nhỗ trợ cập nhật", target: "Creator và shop online muốn tối ưu tốc độ làm việc với tài nguyên số có sẵn..." },
  other: { short: "Sản phẩm có điểm khác biệt rõ ràng, dễ hiểu và dễ tạo thiện cảm.", highlights: "Điểm mạnh rõ\nDễ dùng\nGiá trị thực tế", attrs: "đặc điểm nổi bật\nkích thước cơ bản\nưu điểm chính", target: "Người cần một sản phẩm rõ công năng, dễ dùng, dễ cân nhắc mua..." }
};
