export const routes = {
  login: "/login",
  profile: "/profile",
  admin: "/admin",
  scriptProductInfo: "/scriptProductInfo",
  scriptVideoReview: "/scriptVideoReview",
  api: {
    session: "/api/session",
    authConfig: "/api/auth/config",
    loginPassword: "/api/auth/login-password",
    requestOtp: "/api/auth/request-otp",
    verifyOtp: "/api/auth/verify-otp",
    requestPasswordReset: "/api/auth/request-password-reset",
    verifyPasswordReset: "/api/auth/verify-password-reset",
    changePassword: "/api/auth/change-password",
    logout: "/api/auth/logout",
    favorites: "/api/favorites",
    toggleFavorite: "/api/favorites/toggle",
    history: "/api/history",
    deleteHistory: "/api/history/delete",
    generate: "/api/generate",
    telemetry: "/api/telemetry",
    feedback: "/api/feedback",
    suggestFromImages: "/api/suggest-from-images",
    generateBulk: "/api/generate-bulk",
    generateVideoScript: "/api/generate-video-script",
    googleStart: "/api/auth/google/start",
    adminUsers: "/api/admin/users",
    adminUsersResetPassword: "/api/admin/users/reset-password",
    adminUsersDelete: "/api/admin/users/delete",
    adminAiUsage: "/api/admin/ai-usage",
    adminLaunchMetrics: "/api/admin/launch-metrics"
  }
};
